# Generated by Django 3.2.9 on 2022-10-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255)),
                ('name2', models.CharField(blank=True, max_length=255)),
                ('name3', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('zip1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('vat_ID', models.CharField(max_length=255)),
                ('tax_office_designation', models.CharField(max_length=255)),
                ('tax_office_address', models.CharField(max_length=255)),
            ],
        ),
    ]
