# Generated by Django 3.2.9 on 2022-12-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='tax_office_address',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='tax_office_designation',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='vat_ID',
        ),
    ]
